### ISSUE TITLE
Armor in Kits is equipping in wrong spots when claimed?

### ISSUE THREAD

**Issue by sharkaholic** [nulli0n/SunLight-spigot#19]
Hi there! ^^

I'm currently running 1.20.1 with Sunlight on the Java Edition of Minecraft!

My players are reporting that, upon claiming a kit  in which armor is sat to auto-equip, sat up with the kits module provided in Sunlight, that it's equipping the armor in the wrong spots? So for instance, the boots were on my player's head. :)

Not super important as it's not gamebreaking, but they found it kind of funny and quickly fixed it on their own.

TIA! :)

**Comment by nulli0n** [comment]
Take a look at this https://github.com/nulli0n/SunLight-spigot/wiki/Kits-Module#armor--items-slots and make sure you set up your kit slots the right way.
