### ISSUE TITLE
[Bug] Anvil Deleting Items

### ISSUE THREAD

**Issue by belphegorspn** [nulli0n/SunLight-spigot#22]
`/anvil` deletes an item if you don't take them out before you close the gui.

server version: `git-Purpur-2005 (MC: 1.20.1)`
sunlight version: `3.9.4`

https://github.com/nulli0n/SunLight-spigot/assets/66054833/9ffc94ef-5945-411f-af23-c4805db726b0

**Comment by nulli0n** [comment]
Fixed in v3.9.5
