### ISSUE TITLE
[Feature Request] Teleport delay

### ISSUE THREAD

**Issue by LuckserSky34** [nulli0n/SunLight-spigot#24]
Add the function of being able to add waiting time when teleporting, being able to change the time depending on the player's rank as the Essentials plugin has, this function is essential for a survival pvp server since it will add a higher level of difficulty and it will not be all instant, it will also prevent a player from using /spawn and being instantly teleported out of combat, ideally it would not be able to do that, for example you are following a player and only have a few inches left to hit them and apply the combat tag before it expires, but since it has an instant respawn, it can escape without the player having a chance to hit it again, adding the delay will make the player have to be in a safe zone to use the command.

**Comment by nulli0n** [comment]
See https://github.com/nulli0n/SunLight-spigot/issues/10
