### ISSUE TITLE
[Feature Request] DiscordSRV support for custom Join/leave and death msgs

### ISSUE THREAD

**Issue by LadyHaley** [nulli0n/SunLight-spigot#27]
It would be pretty cool to see these show up in the discord also, in place of the DiscordSRV defaults

**Comment by LadyHaley** [comment]
Bump on this

**Comment by LadyHaley** [comment]
commands being run at the same time would be a good way to at the very least have admins manually add this functionality

**Comment by EarthCow** [comment]
I'm having the same issue
