### ISSUE TITLE
[Feature Request] Expanded Fuctionality for personal player time

### ISSUE THREAD

**Issue by LadyHaley** [nulli0n/SunLight-spigot#28]
When setting a personal player time, I noticed that it would keep the time at that time setting.
I was wondering if you would consider adding a method to allow the personal time to tick along, and if you could also add custom personal time tick speeds to make the day night cycle go real fast or real slow.
Thanks in advanced for your consideration

**Comment by nulli0n** [comment]
Time tick fixed in v3.10.0. Other features are planned to do
