### ISSUE TITLE
Bug: Locale Translation are not working

### ISSUE THREAD

**Issue by Pachecon22** [nulli0n/SunLight-spigot#36]
Good afternoon, I am translating the plugin into the ES language and making the messages to my liking, but when I reload the plugin, the messages that I have changed remain the same as before, or even remain in English although I have set them in the configuration. since it uses the ES language.
I await your response, thank you.

**Comment by nulli0n** [comment]
You made a syntax mitake. Check your config in https://yaml-online-parser.appspot.com/
