### ISSUE TITLE
TAB Module player nametag

### ISSUE THREAD

**Issue by thunder-red-star** [nulli0n/SunLight-spigot#37]
I'm not 100% sure how the Minecraft protocol works in regard to this, but would it be possible to specify "none" as a color, and make it so the prefix's formatting can affect the display name?

![image](https://github.com/nulli0n/SunLight-spigot/assets/67127399/25997477-f59c-440f-9db8-3afa44b587c2)

My goal is to make my name the same color as the rank name before it. This is set up properly in the tab list.

![image](https://github.com/nulli0n/SunLight-spigot/assets/67127399/6ed136a3-7520-4aa5-81ed-476a215e3ce0)

**Comment by nulli0n** [comment]
No way unfortunately, nametags are not really customizable (game limitations) and does not supports HEX colors even. Let me know if I'mw rong and there is any plugins with such feature.
