### ISSUE TITLE
[Bug] Command Cooldowns stay even if command fails

### ISSUE THREAD

**Issue by ghost** [nulli0n/SunLight-spigot#44]
# Description
Example 1: `/rtp`. If the RTP Location is not found then command fails but cooldown is till applied.
Example 2: `/home <xyz>` or `/warp <xyz>`. If the Home/Warp is not found then command fails but cooldown is till applied.
Example 3: `/tpa <xyz>` or `/tpi <xyz>`. If the Player is not found then command fails but cooldown is till applied.

# Steps to Reproduce
1. Configure command cooldowns.
2. Execute the respective command and wait for failure.
3. Try to execute it again, but find out that cooldown is applied.
 
# Server Info
```
Current: git-Purpur-2095 (MC: 1.20.2)*
DiscordSRV version 1.27.0
SunLight version 3.10.1
NexEngine version 2.2.12
```

# Configs
![image](https://github.com/nulli0n/SunLight-spigot/assets/97077949/eed9413f-94f3-48d1-b145-9339e4a32dd2)
![image](https://github.com/nulli0n/SunLight-spigot/assets/97077949/db6caa82-f1b8-4beb-b469-221038283db3)
![image](https://github.com/nulli0n/SunLight-spigot/assets/97077949/5ad82b47-d3af-43ad-a656-ec37551b72c0)

**Comment by nulli0n** [comment]
Not possible to fix, server does not return results of the commands.
