### ISSUE TITLE
how to disable the channel feature alone

### ISSUE THREAD

**Issue by Dreamtell** [nulli0n/SunLight-spigot#46]
I really liked your plugin, I even thought this could be the new EssentialsX replacement, but I ran into some issues that I found a little annoying, that's the Channels feature, I can't find a way to disable it without having to do it. deactivate it. the entire Chat module. On the other hand, I didn't see anywhere how to get the Nametag system to work and what permission it requires to display. I looked in the plugin documentation and nothing.

**Comment by thunder-red-star** [comment]
https://github.com/nulli0n/SunLight-spigot/wiki/Chat-Module#-faq
