### ISSUE TITLE
Completely disabling the chat channel function

### ISSUE THREAD

**Issue by Milarsh** [nulli0n/SunLight-spigot#50]
It is worth adding the ability to completely disable the function of chat channels so that they do not interfere with the work of other chat plugins (in particular TownyChat). There are many other useful features in the chat module, but they cannot be used together with TownyChat

**Comment by ASHISK404** [comment]
I think it's a good idea, disabling the chat module in config.yml doesn't seem to be able to completely disable it, it prevents mods like emogg from sending emojis...

**Comment by nulli0n** [comment]
Won't add. Chat module features are not intended to handle other chat plugins.
