### ISSUE TITLE
Idea: simplified versions of commands to replace the usual ones from Minecraft

### ISSUE THREAD

**Issue by beachvisitor** [nulli0n/SunLight-spigot#51]
There are many different commands in Minecraft with unclear uses for beginners. I would like to suggest adding the same commands to this plugin, but simplified and perhaps even with more functionality. For example, the CMI has the /titlemsg command, it does the same thing as the regular vanilla /title command, but it is easier to use and adds the ability to set the animation speed of the title's appearance, disappearance, and duration. It's really very convenient.

Just as for me, the plugin lacks silent commands (For example: /ban player -s). They exist, but unfortunately not everywhere.

**Comment by nulli0n** [comment]
CMI commands are overcomplicated, I'd say even worse than any other ones. And most of vanilla oness are more than fine imo.
Silent commands were fully implemented in v3.12.0 (dev build is available in the discord)
