### ISSUE TITLE
Suggestion & Request

### ISSUE THREAD

**Issue by emirhann-aydinn** [nulli0n/SunLight-spigot#52]
- Sunlight should support other popular chat plugins. In others, the "/ignore" chat that the player runs will not block and will remain dysfunctional.

- There must be a setting in the Skyblock that prevents running the "/sethome" command on others' island. (Such as SuperiorSkyblock2, BentoBox)

- A feature can be added to the configuration to be able to translate time units into the desired language. (en: seconds - fr: as an example)

**Note:** I'm sorry that my English is bad. I don't know how good the translation will be, I hope you understand what I'm saying.

**Comment by nulli0n** [comment]
1. Fixed in v3.12.0 (dev build is available in the discord)
2. Already implemented (an option to check build access).
3. In /nightcore/lang
