### ISSUE TITLE
Oversight on homesadmin doesn't have permission requirement check

### ISSUE THREAD

**Issue by CactusTheGuy** [nulli0n/SunLight-spigot#57]
### **Explanation:**
When you type **/homesadmin help** or **/homesadmin**, the plugin does not have a permission requirement check to check if player have permission to tab complete and execute the command.
### **Way to reproduce:**

1. Start a fresh paper server (any version) with **sunlight** installed.
2. Enter the the server and type **/homesadmin help** or **/homesadmin** **_without being an operator_**.
3. An list of sub-command show up for **homesadmin** command.

Note: the player is permited to tab completion the command even without the required permission

### Server core: 
Paper 1.19.4

**Comment by nulli0n** [comment]
Fixed in v3.12.0 (dev build is available in the discord)
