### ISSUE TITLE
Support for Minecraft 1.20.6?

### ISSUE THREAD

**Issue by TrueMB** [nulli0n/SunLight-spigot#60]
Is the Support for version 1.20.6 planed?

**Comment by Cqmmls** [comment]
Is the Support for version 1.21 planed?

**Comment by TrueMB** [comment]
Nulli0n updated the Spigot Sunlight title to "big update 50% done".

I expect the integration in the newer system "Nightcore" and not any more the old "nexengine"

Nightcore is already on 1.21.

So it will be. But depending on the progress from 40%-50%, it will take 1-2 months for the release.

**Comment by Cqmmls** [comment]
Exciting good news

**Comment by nulli0n** [comment]
dev build is available in discord.
