### ISSUE TITLE
[Functional Requirements] Missing dependency from nightcore

### ISSUE THREAD

**Issue by mordisk10** [nulli0n/SunLight-spigot#64]
Thanks for creating and also maintaining this plugin, i have just started using it and made the whole configurations.

Also i was experimenting and adding new stuff to the code but since the latest update 3.12.0 i can't compile the plugin because of the latest changes in nightcore that's not pushed yet to github. i guess the only class is `UpdateEntity` afaik.

**Comment by nulli0n** [comment]
Updated.
