### ISSUE TITLE
It is not possible to return to the Overworld from the End using the Exit portal

### ISSUE THREAD

**Issue by hseermc** [nulli0n/SunLight-spigot#66]
when i go into Exit portal,i am teleported in Exit portal again and i can't return to overworld

what should i do? which config should i change or is it a bug? I read all the wiki but none of it

**Comment by nulli0n** [comment]
wtf is "Exit portal"

**Comment by hseermc** [comment]
means go to overworld portalwhen you kill the dragon . i don't know the name in English(sorry my poor English
![image](https://github.com/user-attachments/assets/43ec9579-e70c-47f9-85ce-c837e99ff878)

**Comment by nulli0n** [comment]
Just tested, works fine for me. Must be other plugin issue.
