### ISSUE TITLE
[Feature Request] When a player kill another player, display the weapon used. 

### ISSUE THREAD

**Issue by Noogear** [nulli0n/SunLight-spigot#69]
When a player kill another player, display the weapon used. Hovering the mouse over the item name will show its stats, similar to how it is implemented in the vanilla Minecraft.
![QQ_1722193344471](https://github.com/user-attachments/assets/8f28c5fb-e46d-4197-8194-2bcf2ceebbd5)

**Comment by nulli0n** [comment]
%item%

**Comment by Noogear** [comment]
> %item%

It doesn't work. Only the weapon name can be displayed, and data such as the lore of the item cannot be viewed.
