### ISSUE TITLE
Sunlight error

### ISSUE THREAD

**Issue by Fogrine** [nulli0n/SunLight-spigot#73]
![eb6b6728eb8bc6ef1a715b2b4ca21ea7](https://github.com/user-attachments/assets/e3b92c4b-f5e9-4ed7-aef2-2f984678a07b)
protocollib 5.2.0
server version paper 1.20.4
nightcore 2.6.3

**Comment by nulli0n** [comment]
https://ci.dmulloy2.net/job/ProtocolLib/
