### ISSUE TITLE
Warp Module error

### ISSUE THREAD

**Issue by GalaxyGamerYT** [nulli0n/SunLight-spigot#8]
https://pastebin.com/QbTzA5eQ

**Comment by nulli0n** [comment]
Config syntax error, check it here: https://yaml-online-parser.appspot.com/

**Comment by GalaxyGamerYT** [comment]
Which config is the error coming from.
If it's warps/settings.yml then this is the contents:
`Warp:
  Teleport:
    Cost:
      Money:
        Transfer_To_Owner: true
  Set:
    World_Blacklist:
      - events
      - spawn
    Amount_Per_Group:
      default: 1
      hero: 5
      champion: 10
      myth: 15
      legend: 25
      immortal: -1
      mod: -1
      admin: -1
      dev: -1
      owner: -1
  Rating:
    Scale_Of: 100.0
    Visit_Count_Cooldown: 3600
    Visit_Max_Value: 10000

Editor:
  Description:
    Max_Line_Length: 50
    Max_Line_Amount: 5`
