### ISSUE TITLE
[Bug] In versions above 1.21, there is a problem with itemshow. It won't display NBT data.

### ISSUE THREAD

**Issue by Noogear** [nulli0n/SunLight-spigot#80]
In the chat, when using "@hand", the item name can be obtained normally, but the lore cannot be obtained.

**Comment by Micalhl** [comment]
How about enchants? I’ve encountered the same problem.

**Comment by nulli0n** [comment]
Duplicate https://github.com/nulli0n/SunLight-spigot/issues/75
